# Generated by Django 5.1.7 on 2025-06-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_product_slug_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
